// GENERATED BY uniffi-bindgen — 由 scripts/build-core-ios.sh 生成，勿手改
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CLONE_METRONOME
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CLONE_METRONOME
void*_Nonnull uniffi_tunar_core_fn_clone_metronome(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FREE_METRONOME
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FREE_METRONOME
void uniffi_tunar_core_fn_free_metronome(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CONSTRUCTOR_METRONOME_NEW
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CONSTRUCTOR_METRONOME_NEW
void*_Nonnull uniffi_tunar_core_fn_constructor_metronome_new(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_IS_RUNNING
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_IS_RUNNING
int8_t uniffi_tunar_core_fn_method_metronome_is_running(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_RENDER
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_RENDER
RustBuffer uniffi_tunar_core_fn_method_metronome_render(void*_Nonnull ptr, uint32_t frames, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_ACCENTS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_ACCENTS
void uniffi_tunar_core_fn_method_metronome_set_accents(void*_Nonnull ptr, RustBuffer accents, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_BPM
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_BPM
void uniffi_tunar_core_fn_method_metronome_set_bpm(void*_Nonnull ptr, double bpm, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_CLICK_SAMPLES
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_CLICK_SAMPLES
void uniffi_tunar_core_fn_method_metronome_set_click_samples(void*_Nonnull ptr, RustBuffer accent, RustBuffer normal, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_TIME_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_SET_TIME_SIGNATURE
void uniffi_tunar_core_fn_method_metronome_set_time_signature(void*_Nonnull ptr, uint8_t beats, uint8_t unit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_START
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_START
void uniffi_tunar_core_fn_method_metronome_start(void*_Nonnull ptr, uint64_t at_sample, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_STOP
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_STOP
void uniffi_tunar_core_fn_method_metronome_stop(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_TAP
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_METRONOME_TAP
double uniffi_tunar_core_fn_method_metronome_tap(void*_Nonnull ptr, uint64_t timestamp_samples, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CLONE_TUNARENGINE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CLONE_TUNARENGINE
void*_Nonnull uniffi_tunar_core_fn_clone_tunarengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FREE_TUNARENGINE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FREE_TUNARENGINE
void uniffi_tunar_core_fn_free_tunarengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CONSTRUCTOR_TUNARENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_CONSTRUCTOR_TUNARENGINE_NEW
void*_Nonnull uniffi_tunar_core_fn_constructor_tunarengine_new(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_ANALYZE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_ANALYZE
RustBuffer uniffi_tunar_core_fn_method_tunarengine_analyze(void*_Nonnull ptr, RustBuffer pcm, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_FEED
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_FEED
RustBuffer uniffi_tunar_core_fn_method_tunarengine_feed(void*_Nonnull ptr, RustBuffer pcm, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_LIST_REFERENCE_TONES
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_LIST_REFERENCE_TONES
RustBuffer uniffi_tunar_core_fn_method_tunarengine_list_reference_tones(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_A4
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_A4
void uniffi_tunar_core_fn_method_tunarengine_set_a4(void*_Nonnull ptr, double hz, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_NOISE_GATE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_NOISE_GATE
void uniffi_tunar_core_fn_method_tunarengine_set_noise_gate(void*_Nonnull ptr, float dbfs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_SOLFEGE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_SOLFEGE
void uniffi_tunar_core_fn_method_tunarengine_set_solfege(void*_Nonnull ptr, RustBuffer system, RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_TEMPERAMENT
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_METHOD_TUNARENGINE_SET_TEMPERAMENT
void uniffi_tunar_core_fn_method_tunarengine_set_temperament(void*_Nonnull ptr, uint8_t divisions, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_CENTS_BETWEEN
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_CENTS_BETWEEN
RustBuffer uniffi_tunar_core_fn_func_cents_between(double freq_hz, double target_hz, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_LIST_FINGERING_CHARTS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_LIST_FINGERING_CHARTS
RustBuffer uniffi_tunar_core_fn_func_list_fingering_charts(RustBuffer instrument_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_LIST_INSTRUMENTS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_LIST_INSTRUMENTS
RustBuffer uniffi_tunar_core_fn_func_list_instruments(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_LIST_TUNINGS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_LIST_TUNINGS
RustBuffer uniffi_tunar_core_fn_func_list_tunings(RustBuffer instrument_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_SOLFEGE_FOR_MIDI
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_FN_FUNC_SOLFEGE_FOR_MIDI
RustBuffer uniffi_tunar_core_fn_func_solfege_for_midi(RustBuffer system, RustBuffer key, int32_t midi, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_tunar_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_tunar_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_FREE
void ffi_tunar_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_tunar_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U8
void ffi_tunar_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U8
void ffi_tunar_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U8
void ffi_tunar_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_tunar_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I8
void ffi_tunar_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I8
void ffi_tunar_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I8
void ffi_tunar_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_tunar_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U16
void ffi_tunar_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U16
void ffi_tunar_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U16
void ffi_tunar_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_tunar_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I16
void ffi_tunar_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I16
void ffi_tunar_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I16
void ffi_tunar_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_tunar_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U32
void ffi_tunar_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U32
void ffi_tunar_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U32
void ffi_tunar_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_tunar_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I32
void ffi_tunar_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I32
void ffi_tunar_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I32
void ffi_tunar_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_tunar_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_U64
void ffi_tunar_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_U64
void ffi_tunar_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_U64
void ffi_tunar_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_tunar_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_I64
void ffi_tunar_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_I64
void ffi_tunar_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_I64
void ffi_tunar_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_tunar_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_F32
void ffi_tunar_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_F32
void ffi_tunar_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_F32
void ffi_tunar_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_tunar_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_F64
void ffi_tunar_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_F64
void ffi_tunar_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_F64
void ffi_tunar_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_tunar_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_POINTER
void ffi_tunar_core_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_POINTER
void ffi_tunar_core_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_POINTER
void ffi_tunar_core_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_tunar_core_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_tunar_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_tunar_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_tunar_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_tunar_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_POLL_VOID
void ffi_tunar_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_tunar_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_FREE_VOID
void ffi_tunar_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_tunar_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_CENTS_BETWEEN
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_CENTS_BETWEEN
uint16_t uniffi_tunar_core_checksum_func_cents_between(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_LIST_FINGERING_CHARTS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_LIST_FINGERING_CHARTS
uint16_t uniffi_tunar_core_checksum_func_list_fingering_charts(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_LIST_INSTRUMENTS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_LIST_INSTRUMENTS
uint16_t uniffi_tunar_core_checksum_func_list_instruments(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_LIST_TUNINGS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_LIST_TUNINGS
uint16_t uniffi_tunar_core_checksum_func_list_tunings(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_SOLFEGE_FOR_MIDI
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_FUNC_SOLFEGE_FOR_MIDI
uint16_t uniffi_tunar_core_checksum_func_solfege_for_midi(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_IS_RUNNING
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_IS_RUNNING
uint16_t uniffi_tunar_core_checksum_method_metronome_is_running(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_RENDER
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_RENDER
uint16_t uniffi_tunar_core_checksum_method_metronome_render(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_ACCENTS
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_ACCENTS
uint16_t uniffi_tunar_core_checksum_method_metronome_set_accents(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_BPM
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_BPM
uint16_t uniffi_tunar_core_checksum_method_metronome_set_bpm(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_CLICK_SAMPLES
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_CLICK_SAMPLES
uint16_t uniffi_tunar_core_checksum_method_metronome_set_click_samples(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_TIME_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_SET_TIME_SIGNATURE
uint16_t uniffi_tunar_core_checksum_method_metronome_set_time_signature(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_START
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_START
uint16_t uniffi_tunar_core_checksum_method_metronome_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_STOP
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_STOP
uint16_t uniffi_tunar_core_checksum_method_metronome_stop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_TAP
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_METRONOME_TAP
uint16_t uniffi_tunar_core_checksum_method_metronome_tap(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_ANALYZE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_ANALYZE
uint16_t uniffi_tunar_core_checksum_method_tunarengine_analyze(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_FEED
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_FEED
uint16_t uniffi_tunar_core_checksum_method_tunarengine_feed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_LIST_REFERENCE_TONES
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_LIST_REFERENCE_TONES
uint16_t uniffi_tunar_core_checksum_method_tunarengine_list_reference_tones(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_A4
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_A4
uint16_t uniffi_tunar_core_checksum_method_tunarengine_set_a4(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_NOISE_GATE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_NOISE_GATE
uint16_t uniffi_tunar_core_checksum_method_tunarengine_set_noise_gate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_SOLFEGE
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_SOLFEGE
uint16_t uniffi_tunar_core_checksum_method_tunarengine_set_solfege(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_TEMPERAMENT
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_METHOD_TUNARENGINE_SET_TEMPERAMENT
uint16_t uniffi_tunar_core_checksum_method_tunarengine_set_temperament(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_CONSTRUCTOR_METRONOME_NEW
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_CONSTRUCTOR_METRONOME_NEW
uint16_t uniffi_tunar_core_checksum_constructor_metronome_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_CONSTRUCTOR_TUNARENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_TUNAR_CORE_CHECKSUM_CONSTRUCTOR_TUNARENGINE_NEW
uint16_t uniffi_tunar_core_checksum_constructor_tunarengine_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TUNAR_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_TUNAR_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_tunar_core_uniffi_contract_version(void
    
);
#endif

