#!/bin/bash
# build-core-ios.sh — 编译 Rust core 为 iOS 静态库 + UniFFI Swift 绑定 + XCFramework。
#
# 输出：
#   ios/TunerCore/tuner_core.xcframework/      (device arm64 + simulator arm64)
#   ios/TunerCore/Sources/TunerCore/           (UniFFI 生成的 Swift 绑定 + 头文件，勿手改)
#
# 依赖：cargo（targets aarch64-apple-ios / aarch64-apple-ios-sim）、xcodebuild。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CORE="$ROOT/core"
IOS="$ROOT/ios"
FW="$IOS/TunerCore"
GEN="$FW/Sources/TunerCore"

echo ">> 1/4 编译 staticlib (device + sim)"
(cd "$CORE" && cargo build --release --target aarch64-apple-ios)
(cd "$CORE" && cargo build --release --target aarch64-apple-ios-sim)

DEV_A="$CORE/target/aarch64-apple-ios/release/libtuner_core.a"
SIM_A="$CORE/target/aarch64-apple-ios-sim/release/libtuner_core.a"
[[ -f "$DEV_A" && -f "$SIM_A" ]] || { echo "错误：缺少 staticlib 输出" >&2; exit 1; }

echo ">> 2/4 生成 UniFFI Swift 绑定 → $GEN"
rm -rf "$GEN"
mkdir -p "$GEN"
(cd "$CORE" && cargo run --quiet --bin uniffi-bindgen -- generate \
    --library "$SIM_A" \
    --language swift \
    --out-dir "$GEN")
# 头注 generated 勿手改
find "$GEN" -type f \( -name '*.swift' -o -name '*.h' \) | while read -r f; do
    tmp="$f.tmp"
    { echo "// GENERATED BY uniffi-bindgen — 由 scripts/build-core-ios.sh 生成，勿手改"; cat "$f"; } > "$tmp"
    mv "$tmp" "$f"
done
ls "$GEN"

echo ">> 3/4 打包 XCFramework"
rm -rf "$FW/tuner_core.xcframework"
xcodebuild -create-xcframework \
    -library "$DEV_A" -headers "$GEN" \
    -library "$SIM_A" -headers "$GEN" \
    -output "$FW/tuner_core.xcframework"

echo ">> 4/4 完成"
find "$FW/tuner_core.xcframework" -maxdepth 2 -name 'libtuner_core.a' -o -maxdepth 2 -type d | sort
