#!/bin/bash
# build-core-android.sh — 编译 Rust core 为 Android 各 ABI 的 .so，并生成 UniFFI Kotlin 绑定。
#
# 输出：
#   android/core-binding/src/main/jniLibs/<abi>/libtunar_core.so
#   android/core-binding/src/main/kotlin/generated/  (UniFFI 生成的 Kotlin 绑定，勿手改)
#
# 依赖：cargo、cargo-ndk（缺失时自动安装）、ANDROID_NDK_HOME（未设置时自动探测最新 NDK）。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CORE="$ROOT/core"
BINDING="$ROOT/android/core-binding"
JNILIBS="$BINDING/src/main/jniLibs"
KOTLIN_OUT="$BINDING/src/main/kotlin/generated"
ABIS=(arm64-v8a armeabi-v7a x86_64)

# ---- 1. 探测 NDK ----
if [[ -z "${ANDROID_NDK_HOME:-}" ]]; then
    SDK="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
    for dir in "$SDK/ndk" "$SDK/ndk-bundle"; do
        if [[ -d "$dir" ]]; then
            # 取版本号最大者
            NDK="$(ls -1 "$dir" | sort -t. -k1,1nr -k2,2nr -k3,3nr | head -1 || true)"
            if [[ -n "$NDK" ]]; then
                export ANDROID_NDK_HOME="$dir/$NDK"
                break
            fi
        fi
    done
fi
if [[ -z "${ANDROID_NDK_HOME:-}" || ! -d "${ANDROID_NDK_HOME:-/nonexistent}" ]]; then
    echo "错误：未找到 Android NDK。请安装 NDK 或设置 ANDROID_NDK_HOME。" >&2
    exit 1
fi
echo ">> NDK: $ANDROID_NDK_HOME"

# ---- 2. 检查 cargo-ndk ----
if ! cargo ndk --version >/dev/null 2>&1; then
    echo ">> 未找到 cargo-ndk，执行 cargo install cargo-ndk ..."
    cargo install cargo-ndk
fi
echo ">> cargo-ndk: $(cargo ndk --version)"

# ---- 3. 编译各 ABI 的 cdylib ----
echo ">> 编译 Rust core (release) → $JNILIBS"
mkdir -p "$JNILIBS"
(cd "$CORE" && cargo ndk \
    -t arm64-v8a -t armeabi-v7a -t x86_64 \
    -o "$JNILIBS" \
    build --release)

for abi in "${ABIS[@]}"; do
    if [[ ! -f "$JNILIBS/$abi/libtunar_core.so" ]]; then
        echo "错误：缺少 $JNILIBS/$abi/libtunar_core.so" >&2
        exit 1
    fi
done
echo ">> .so 就绪: ${ABIS[*]}"

# ---- 4. 生成 Kotlin 绑定 ----
echo ">> 生成 UniFFI Kotlin 绑定 → $KOTLIN_OUT"
rm -rf "$KOTLIN_OUT"
mkdir -p "$KOTLIN_OUT"
(cd "$CORE" && cargo run --quiet --bin uniffi-bindgen -- generate \
    --library "$JNILIBS/arm64-v8a/libtunar_core.so" \
    --language kotlin \
    --out-dir "$KOTLIN_OUT")

# 头注 generated 勿手改
find "$KOTLIN_OUT" -name '*.kt' | while read -r f; do
    tmp="$f.tmp"
    { echo "// GENERATED BY uniffi-bindgen — 由 scripts/build-core-android.sh 生成，勿手改"; cat "$f"; } > "$tmp"
    mv "$tmp" "$f"
done

echo ">> 完成。绑定文件："
find "$KOTLIN_OUT" -name '*.kt' -exec basename {} \;
